### ISSUE TITLE
matplotlib support

### ISSUE THREAD

**Issue by tdegeus** [h5preserve/h5preserve#113]
Following your mention here : https://github.com/h5py/h5py/issues/1769

I'm not sure if I'm understanding the extent of this library at first glance. But from what it seems it can save custom data formats. I was wondering if you ever explored saving crucial data (data points, color, linestyle) from matplotlib handles?

**Comment by aragilar** [comment]
Not for matplotlib, as either the data is already stored in a file, and I'd use matplotlib's style support for the rest. Also, that would make the loaders/dumpers much more tied to matplotlib's class hierarchy, making them much less robust. If you want to dump arbitrary objects to HDF5, https://github.com/telegraphic/hickle or https://github.com/DaanVanVugt/h5pickle might be better choices (as they are more pickle-like, h5preserve instead follows the philosophy outlined at https://eev.ee/release/2015/10/15/dont-use-pickle-use-camel/).
